baseDir: tmp

tags:
  databases:
    Documents:
      desc: Document identifier labels used to identify each document
      localPath: $baseDir/Documents.sqlite
      baseUrl: 'docs'
      logLevel: 10
    CrossReferences:
      desc: Cross reference labels used across the collection of Typst documents
      localPath: $baseDir/CrossReferences.sqlite
      baseUrl: 'cr'
      logLevel: 10
  webserver:
    title: Typst document label databases
    # for some reason Waitress needs this when inside a Podman container!
    #host: '0.0.0.0'
    host: '127.0.0.1'
    port: 8890
    appLogLevel: 10
    waitressLogLevel: 10
    flaskLogLevel: 10
